### ISSUE TITLE
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kimkj38** [SxJyJay/MORE#1]
Thanks for your great work.

I set up according to [Scan2Cap](https://github.com/daveredrum/Scan2Cap) but got OSError.

My setting is Ubuntu 18.04, CUDA 10.2, pytorch 1.8.0

Could you tell me how did you set up?

**Comment by SxJyJay** [comment]
I guess it may be caused by the inconsistency between precompiled pointnet and run-time cuda versions.  Can you provide more error information?

**Comment by kimkj38** [comment]
@SxJyJay 
![image](https://user-images.githubusercontent.com/76815825/218397713-3a418c2d-09f7-4c13-89af-1cecccd69f61.png)

I attached error information. Is it related with torch-geometric?

https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html
Official PyG installation web-site only provides for pytorch 1.12, 1.13 so, I referenced below explanation and installed with commands:
https://blog.csdn.net/weixin_47779152/article/details/120570367
- `pip install https://data.pyg.org/whl/torch-1.8.0%2Bcu102/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl`
- `pip install https://data.pyg.org/whl/torch-1.8.0%2Bcu102/torch_scatter-2.0.6-cp38-cp38-linux_x86_64.whl`
- `pip install https://data.pyg.org/whl/torch-1.8.0%2Bcu102/torch_sparse-0.6.10-cp38-cp38-linux_x86_64.whl`
- `pip install https://data.pyg.org/whl/torch-1.8.0%2Bcu102/torch_spline_conv-1.2.1-cp38-cp38-linux_x86_64.whl`

**Comment by SxJyJay** [comment]
It seems that your torch_sparse is built by CUDA 11.0. You can checkout the history version (e.g., 1.7.2) of torch-geometric to find the installation command compatible with torch 1.8.

**Comment by kimkj38** [comment]
@SxJyJay Thanks for your help. I solved it. 
And I'm sorry but have one more question about AttributeError.
self.\__explain\__ and self.\__edge_mask\__ are not defined in your code and makes the error. How can I handle it?

Removing 'if' statement is okay?


![image](https://user-images.githubusercontent.com/76815825/218412443-d713db51-718a-4631-a57d-025fa328c632.png)
![image](https://user-images.githubusercontent.com/76815825/218412548-40f1b86b-3980-4d03-b0c3-4e9a1ee50333.png)

**Comment by SxJyJay** [comment]
Methods like "self._explain_" and "self._edge_mask_ " are defined in the class "MessagePassing". The above errors may be caused by the incompatibility of different versions of pyg. I list my environment requirements below. Hope it helps.
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://repo.anaconda.com/pkgs/main
_openmp_mutex             4.5                       1_gnu    https://repo.anaconda.com/pkgs/main
absl-py                   1.0.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
boto3                     1.21.27                  pypi_0    pypi
botocore                  1.24.27                  pypi_0    pypi
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.14.6           py38h400218f_0    https://repo.anaconda.com/pkgs/main
charset-normalizer        2.0.10             pyhd8ed1ab_0    conda-forge
click                     8.0.4                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda-pack                0.6.0                    pypi_0    pypi
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
cudatoolkit               11.1.1               h6406543_8    conda-forge
cycler                    0.11.0                   pypi_0    pypi
decorator                 4.4.2                      py_0    conda-forge
easydict                  1.9                      pypi_0    pypi
editdistpy                0.1.3                    pypi_0    pypi
elevate                   0.1.3                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.28.5                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
grpcio                    1.43.0                   pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
idna                      3.1                pyhd3deb0d_0    conda-forge
imageio                   2.13.5                   pypi_0    pypi
importlib-metadata        4.10.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    https://repo.anaconda.com/pkgs/main
ipdb                      0.13.9                   pypi_0    pypi
ipython                   7.31.0                   pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.0                    pypi_0    pypi
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2    https://repo.anaconda.com/pkgs/main
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 h3be6417_0    https://repo.anaconda.com/pkgs/main
ld_impl_linux-64          2.35.1               h7274673_9    https://repo.anaconda.com/pkgs/main
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           5_h92ddd45_netlib    conda-forge
libffi                    3.3                  he6710b0_2    https://repo.anaconda.com/pkgs/main
libgcc-ng                 9.3.0               h5101ec6_17    https://repo.anaconda.com/pkgs/main
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   9.3.0               h5101ec6_17    https://repo.anaconda.com/pkgs/main
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17    https://repo.anaconda.com/pkgs/main
libtiff                   4.1.0                h2733197_1    https://repo.anaconda.com/pkgs/main
libuv                     1.42.0               h7f98852_0    conda-forge
libwebp                   1.2.0                h89dd481_0    https://repo.anaconda.com/pkgs/main
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mkl                       2020.2                      256    https://repo.anaconda.com/pkgs/main
mkl-service               2.3.0            py38h1e0a361_2    conda-forge
mkl_fft                   1.2.0            py38hab2c0dc_1    conda-forge
mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
ncurses                   6.3                  h7f8727e_2    https://repo.anaconda.com/pkgs/main
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.19.2           py38h54aff64_0    https://repo.anaconda.com/pkgs/main
numpy-base                1.19.2           py38hfa32c7d_0    https://repo.anaconda.com/pkgs/main
numpy-quaternion          2021.11.4.15.26.3          pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.5.62                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1l               h7f8727e_0    https://repo.anaconda.com/pkgs/main
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.5            py38h1abd341_0    conda-forge
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0    https://repo.anaconda.com/pkgs/main
plyfile                   0.7.4                    pypi_0    pypi
pointnet2                 3.0.0                    pypi_0    pypi
prompt-toolkit            3.0.24                   pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyg                       2.0.1           py38_torch_1.8.0_cu111    pyg
pygments                  2.11.2                   pypi_0    pypi
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12               h12debd9_0    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py38_torch_1.8.0_cu111    pyg
pytorch-scatter           2.0.8           py38_torch_1.8.0_cu111    pyg
pytorch-sparse            0.6.12          py38_torch_1.8.0_cu111    pyg
pytorch-spline-conv       1.2.1           py38_torch_1.8.0_cu111    pyg
pytorch-transformers      1.2.0                    pypi_0    pypi
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1                  h27cfd23_0    https://repo.anaconda.com/pkgs/main
regex                     2022.3.15                pypi_0    pypi
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
s3transfer                0.5.2                    pypi_0    pypi
sacremoses                0.0.49                   pypi_0    pypi
scikit-learn              0.24.2           py38hdc147b9_0    conda-forge
scipy                     1.7.3                    pypi_0    pypi
sentencepiece             0.1.96                   pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0    https://repo.anaconda.com/pkgs/main
shapely                   1.8.1.post1              pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               hc218d9a_0    https://repo.anaconda.com/pkgs/main
symspellpy                6.7.6                    pypi_0    pypi
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.4.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h1ccaba5_0    https://repo.anaconda.com/pkgs/main
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu111    pytorch
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1                    pypi_0    pypi
trimesh                   2.35.39                  pypi_0    pypi
typing_extensions         4.0.1              pyha770c72_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/main
xz                        5.2.5                h7b6447c_0    https://repo.anaconda.com/pkgs/main
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4    https://repo.anaconda.com/pkgs/main
zstd                      1.4.9                ha95c52a_0    conda-forge
```

**Comment by kimkj38** [comment]
@SxJyJay I succeeded to start training. Thank you:)

**Comment by SxJyJay** [comment]
OK, I close this issue.
